---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true
configure_postgres: true
configure_vscode: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Launchpad
 - Safari
 - Messages
 - TV
 - Podcasts
 - 'App Store'
 - Mail
 - Maps
 - Photos
 - FaceTime
 - Calendar
 - Contacts
 - Reminders
 - Notes
 - Music
 - Keynote
 - Numbers
 - Pages
 - 'System Preferences'
dockitems_persist:
 - name: "Sidekick"
   path: "/Applications/Sidekick.app/"
   pos: 2
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 3
 - name: "Spotify"
   path: "/Applications/Spotify.app/"
   pos: 4

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/jaulz/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/projects/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
#  - .config/starship.toml
  - .config/fish/config.fish

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - awscli
  - bash-completion
  - blueutil
  - cocoapods
  - composer
  - curl
  - doxygen
  - fish
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - imagemagick
  - iperf
  - jq
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - pcre2
  - php@8.0
  - postgis
  - ssh-copy-id
  - readline
  - openssl
#  - starship
  - yarn
  - youtube-dl
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/autoupdate
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - barrier
#  - blackhole-2ch
  - blockblocko
  - calibre
  - chromedriver
  - discord
  - docker
#  - do-not-disturb
  - eqmac
  - firefox
  - font-fira-code
  - gimp
  - google-chrome
  - handbrake
  - inkscape
  - google-drive
  - transmit
  - knockknock
  - lulu
  - maccy
  - microsoft-office-2016
  - ngrok
  - omnidisksweeper
  - oversight
  - pushplaylabs-sidekick
  - reikey
  - spotify
  - sublime-text
  - tableplus
  - the-unarchiver
  - vagrant
  - virtualbox
  - vlc
  - whatsapp
  - wireshark

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
#  - { id: 441258766, name: "Magnet" }
  - { id: 497799835, name: "XCode" }
  - { id: 937984704, name: "Amphetamine" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
 - name: powerline-status
   state: present # present/absent/latest, default: present
omf_packages:
 - name: nvm
   state: present # present/absent/latest, default: present
pecl_packages:
 - name: xdebug
   state: present # present/absent/latest, default: present
 - name: swoole
   state: present # present/absent/latest, default: present

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Install Postgres
postgresql_user_name: postgres
postgresql_version: 11

# Setup vscode
vscode_extensions:
- waderyan.gitblame
- cjhowe7.laravel-blade
- bmewburn.vscode-intelephense-client
- esbenp.prettier-vscode
- johnsoncodehk.volar
- ryannaddy.laravel-artisan
- felixfbecker.php-debug
- GitHub.codespaces
vscode_overwrite_settings: yes
vscode_settings: {
  "editor.fontFamily": "'Fira Code', Consolas, 'Courier New', monospace",
  "editor.fontLigatures": true,
  "editor.tabSize": 2,
  "terminal.integrated.fontFamily": "Roboto Mono for Powerline",
  "terminal.integrated.automationShell.osx": "/bin/sh",
  "terminal.integrated.defaultProfile.osx": "fish",
  "terminal.integrated.profiles.osx": {
      "fish": {
          "path": "fish",
          "args": [
              "-l"
          ]
      }
  },
  "php.validate.executablePath": "/opt/homebrew/opt/php/bin/php",
  "artisan.php.location": "/opt/homebrew/opt/php/bin/php",
  "LaravelExtraIntellisense.phpCommand": "/opt/homebrew/opt/php/bin/php -r \"{code}\"",
  "[vue]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[php]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []