---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: gantsign.visual-studio-code-extensions
  - name: samdoran.fish

collections:
  - name: geerlingguy.mac
