---
- name: Start postgres service
  command: "brew services restart postgresql"

- name: Wait for postgres
  wait_for:
    host: 0.0.0.0
    port: 5432

- name: Create database
  command: "createdb"
  ignore_errors: yes

- name: Remove 
  community.general.launchd:
    name: org.memcached
    state: stopped