---
# Custom Terminal theme.
- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  copy:
    src: files/terminal/JJG-Term.terminal
    dest: /tmp/JJG-Term.terminal
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  command: open /tmp/JJG-Term.terminal
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string JJG-Term
    - defaults write com.apple.terminal 'Startup Window Settings' -string JJG-Term
  changed_when: false
  when: "'JJG-Term' not in terminal_theme.stdout"

- name: Determine fish executable location
  command: which fish
  register: fish

- name: Change default shell
  user: name="{{ ansible_user_id }}" shell="{{ fish.stdout }}"
  become: yes

- name: Add /opt/homebrew/bin to PATH for arm-based Macs
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/paths
    line: /opt/homebrew/bin
    create: yes
  when: ansible_architecture == "arm64"

- name: Install oh-my-fish
  git: repo=https://github.com/oh-my-fish/oh-my-fish.git dest=~/.local/share/omf update=yes

- name: Create fish config
  copy:
    src: files/fish/config.fish
    dest: ~/.config/fish/config.fish

- name: Install oh-my-fish themes and plugins
  command: fish -c "omf install"
  args:
    creates: ~/.local/share/omf/themes/default/
